In [121]:
import pandas as pd

df = pd.read_csv("data_iter1.csv", encoding='UTF-8', sep=',')

In [122]:
df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Payment_Method_Diversity_1.0,Payment_Method_Diversity_2.0,Payment_Method_Diversity_3.0,Payment_Method_Diversity_4.0,Payment_Method_Diversity_5.0,Make_Wishlists,User_Revenue,Lifetime_Per_Year,Gender_code,monthly_income
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,True,False,False,False,False,True,293.958621,328.734483,0,2800
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,False,False,True,False,False,True,1004.859375,667.168750,0,3200
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,False,True,False,False,False,True,519.390345,444.741379,1,3900
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,False,False,True,False,False,True,849.980769,900.353846,1,5200
4,35.0,Male,India,Delhi,3.1,29.0,51.4,8.4,19.1,9.0,...,False,False,False,True,False,True,1481.370968,981.061290,0,450

In [123]:
# для удобства при работе
df.columns = df.columns.str.lower()

In [124]:
df.head()

,age,gender,country,city,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,...,payment_method_diversity_1.0,payment_method_diversity_2.0,payment_method_diversity_3.0,payment_method_diversity_4.0,payment_method_diversity_5.0,make_wishlists,user_revenue,lifetime_per_year,gender_code,monthly_income
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,True,False,False,False,False,True,293.958621,328.734483,0,2800
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,False,False,True,False,False,True,1004.859375,667.168750,0,3200
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,False,True,False,False,False,True,519.390345,444.741379,1,3900
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,False,False,True,False,False,True,849.980769,900.353846,1,5200
4,35.0,Male,India,Delhi,3.1,29.0,51.4,8.4,19.1,9.0,...,False,False,False,True,False,True,1481.370968,981.061290,0,450

### Описание признаков датасета (Добавить новые!)

| Признак | Описание |
|--------|----------|
| **Age** | Возраст пользователя |
| **Gender** | Пол  |
| **Country** | Страна |
| **City** | Город |
| **Membership_Years** | Стаж клиента |
| **Login_Frequency** | Частота входов на сайт |
| **Session_Duration_Avg** | Средняя длительность сессии на сайте |
| **Pages_Per_Session** | Число страниц, просмотренных за сессию |
| **Cart_Abandonment_Rate** | Доля брошенных корзин |
| **Wishlist_Items** | Число товаров в избранном |
| **Email_Open_Rate** | Доля открытия почты |
| **Mobile_App_Usage** | Использование мобильного приложения |
| **Social_Media_Engagement_Score** | Уровень вовлечения через соцсети |
| **Total_Purchases** | Число покупок |
| **Average_Order_Value** | Средний чек при покупке |
| **Days_Since_Last_Purchase** | Давность последней покупки |
| **Discount_Usage_Rate** | Доля заказов со скидкой |
| **Return_Rate** | Доля возвратов |
| **Payment_Method_Diversity** | Число способов оплаты |
| **Customer_Service_Calls** | Звонки в поддержку |
| **Product_Reviews_Written** | Число написанных отзывов |
| **Lifetime_Value** | Выручка |
| **Credit_Balance** | Баланс клиента |
| **Signup_Quarter** | Квартал регистрации |
| **Churned** | Ушел ли клиент? |

В признаках, где строки принимают не более 10 значений.
- Прием из семинара

In [125]:
import numpy as np

df = df.replace({"?": np.nan})

In [126]:
df.isna().sum()

age                              0
gender                           0
country                          0
city                             0
membership_years                 0
login_frequency                  0
session_duration_avg             0
pages_per_session                0
cart_abandonment_rate            0
wishlist_items                   0
total_purchases                  0
average_order_value              0
days_since_last_purchase         0
discount_usage_rate              0
returns_rate                     0
email_open_rate                  0
customer_service_calls           0
product_reviews_written          0
social_media_engagement_score    0
mobile_app_usage                 0
lifetime_value                   0
credit_balance                   0
churned                          0
signup_quarter_q1                0
signup_quarter_q2                0
signup_quarter_q3                0
signup_quarter_q4                0
payment_method_diversity_1.0     0
payment_method_diversity_2.0     0
payment_method_diversity_3.0     0
payment_method_diversity_4.0     0
payment_method_diversity_5.0     0
make_wishlists                   0
user_revenue                     0
lifetime_per_year                0
gender_code                      0
monthly_income                   0
dtype: int64

In [127]:
df.select_dtypes(include = ['object']).columns

Index(['gender', 'country', 'city'], dtype='object')

In [128]:
df = df.dropna()

In [129]:
print(df['gender'].nunique())
df['gender'].value_counts()

3

gender
Female    25116
Male      23947
Other       937
Name: count, dtype: int64

In [130]:
df['country'].value_counts()

country
USA          17384
UK            7534
Canada        6023
Germany       4925
Australia     4061
France        4013
India         3512
Japan         2548
Name: count, dtype: int64

In [131]:
df['city'].unique()

array(['Marseille', 'Manchester', 'Vancouver', 'New York', 'Delhi',
       'Tokyo', 'Berlin', 'Houston', 'Calgary', 'Glasgow', 'Munich',
       'Phoenix', 'Paris', 'Ottawa', 'Los Angeles', 'Bangalore',
       'Adelaide', 'Yokohama', 'Sydney', 'Nagoya', 'Frankfurt', 'Cologne',
       'Hamburg', 'Nice', 'Chicago', 'Toulouse', 'Brisbane', 'Leeds',
       'Mumbai', 'Montreal', 'Melbourne', 'Osaka', 'Lyon', 'Hyderabad',
       'Chennai', 'Birmingham', 'London', 'Toronto', 'Perth', 'Kyoto'],
      dtype=object)

In [132]:
df = pd.get_dummies(
    df,
    columns=['gender', 'country'],
    drop_first=True
)

df.head()

,age,city,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,total_purchases,average_order_value,...,monthly_income,gender_Male,gender_Other,country_Canada,country_France,country_Germany,country_India,country_Japan,country_UK,country_USA
0,43.0,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,9.0,94.72,...,2800,True,False,False,True,False,False,False,False,False
1,36.0,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,19.5,82.45,...,3200,True,False,False,False,False,False,False,True,False
2,45.0,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,9.1,165.52,...,3900,False,False,True,False,False,False,False,False,False
3,56.0,New York,2.6,10.0,38.4,14.8,41.7,9.0,15.0,147.33,...,5200,False,False,False,False,False,False,False,False,True
4,35.0,Delhi,3.1,29.0,51.4,8.4,19.1,9.0,32.5,141.30,...,450,True,False,False,False,False,True,False,False,False

Наш таргет - lifetime_value - выручка от клиента. Кажется что признаки, касающиеся lifetime_per_year, user_revenue.

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 44 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            50000 non-null  float64
 1   city                           50000 non-null  object
 2   membership_years               50000 non-null  float64
 3   login_frequency                50000 non-null  float64
 4   session_duration_avg           50000 non-null  float64
 5   pages_per_session              50000 non-null  float64
 6   cart_abandonment_rate          50000 non-null  float64
 7   wishlist_items                 50000 non-null  float64
 8   total_purchases                50000 non-null  float64
 9   average_order_value            50000 non-null  float64
 10  days_since_last_purchase       50000 non-null  float64
 11  discount_usage_rate            50000 non-null  float64
 12  returns_rate                   50000 non-null  float64
 13  email_open_rate                50000 non-null  float64
 14  customer_service_calls         50000 non-null  float64
 15  product_reviews_written        50000 non-null  float64
 16  social_media_engagement_score  50000 non-null  float64
 17  mobile_app_usage               50000 non-null  float64
 18  lifetime_value                 50000 non-null  float64
 19  credit_balance                 50000 non-null  float64
 20  churned                        50000 non-null  int64
 21  signup_quarter_q1              50000 non-null  bool
 22  signup_quarter_q2              50000 non-null  bool
 23  signup_quarter_q3              50000 non-null  bool
 24  signup_quarter_q4              50000 non-null  bool
 25  payment_method_diversity_1.0   50000 non-null  bool
 26  payment_method_diversity_2.0   50000 non-null  bool
 27  payment_method_diversity_3.0   50000 non-null  bool
 28  payment_method_diversity_4.0   50000 non-null  bool
 29  payment_method_diversity_5.0   50000 non-null  bool
 30  make_wishlists                 50000 non-null  bool
 31  user_revenue                   50000 non-null  float64
 32  lifetime_per_year              50000 non-null  float64
 33  gender_code                    50000 non-null  int64
 34  monthly_income                 50000 non-null  int64
 35  gender_Male                    50000 non-null  bool
 36  gender_Other                   50000 non-null  bool
 37  country_Canada                 50000 non-null  bool
 38  country_France                 50000 non-null  bool
 39  country_Germany                50000 non-null  bool
 40  country_India                  50000 non-null  bool
 41  country_Japan                  50000 non-null  bool
 42  country_UK                     50000 non-null  bool
 43  country_USA                    50000 non-null  bool
dtypes: bool(19), float64(21), int64(3), object(1)
memory usage: 10.4+ MB

Для улучшения результатов модели в дальнейшем будем эксперимаентировать со списком признаков для удаления и сравнивать метрики. Сразу подготовим для этого функцию , возвращающую матрицу объектов-признаков X и таргет y.

In [134]:
cols_to_drop = ["lifetime_value", "user_revenue", "lifetime_per_year", 'city']

def prepare_X_y(df:pd.DataFrame, drop_cols:list[str], target:str="lifetime_value"):
  y = df[target]
  X = df.drop(columns=drop_cols)

  bools = df.select_dtypes(include='bool').columns
  X[bools] = X[bools].astype(int)

  return X, y

## Разделение train - test

In [135]:
X, y = prepare_X_y(df, cols_to_drop)

In [136]:
X.head()

,age,membership_years,login_frequency,session_duration_avg,pages_per_session,cart_abandonment_rate,wishlist_items,total_purchases,average_order_value,days_since_last_purchase,...,monthly_income,gender_Male,gender_Other,country_Canada,country_France,country_Germany,country_India,country_Japan,country_UK,country_USA
0,43.0,2.9,14.0,27.4,6.0,50.6,3.0,9.0,94.72,34.0,...,2800,1,0,0,1,0,0,0,0,0
1,36.0,1.6,15.0,42.7,10.3,37.7,1.0,19.5,82.45,71.0,...,3200,1,0,0,0,0,0,0,1,0
2,45.0,2.9,10.0,24.8,1.6,70.9,1.0,9.1,165.52,11.0,...,3900,0,0,1,0,0,0,0,0,0
3,56.0,2.6,10.0,38.4,14.8,41.7,9.0,15.0,147.33,47.0,...,5200,0,0,0,0,0,0,0,0,1
4,35.0,3.1,29.0,51.4,8.4,19.1,9.0,32.5,141.30,73.0,...,450,1,0,0,0,0,1,0,0,0

In [137]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=13)

## Бейзлайн модели линейной регрессии

In [138]:
from sklearn.linear_model import LinearRegression

In [139]:
def linear_regressor(X_train, y_train, X_test):

  lr = LinearRegression()
  lr.fit(X_train, y_train)

  y_pred = lr.predict(X_test)
  return y_pred

## Бейзлайн модели KNN

In [140]:
from sklearn.neighbors import KNeighborsRegressor

In [141]:
def knn_regressor(X_train, y_train, X_test, n_neighbors=3, p=1):

  knn = KNeighborsRegressor(n_neighbors = n_neighbors, p = p)
  knn.fit(X_train, y_train)

  y_pred = knn.predict(X_test)
  return y_pred

## Функция подсчёта метрик


* Mean Squared Error (MSE): $\frac{1}{n}\sum\limits_i^n(\widetilde{y}_i - y_i)^2$
* Mean Absolute Error (MAE): $\frac{1}{n}\sum\limits_i^n|\widetilde{y}_i - y_i|$
* Max Error: $\max\limits_i |\widetilde{y}_i - y_i|$

где $\widetilde{y}$ — предсказанное значение, $y$ — реальное значение.

In [142]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, max_error
from sklearn.metrics import r2_score, mean_absolute_percentage_error

In [143]:
def show_metrics(y_test, y_pred):

  print("MSE: ", mean_squared_error(y_test, y_pred))
  print("MAE: ", mean_absolute_error(y_test, y_pred))
  print("MAX_ERROR: ", max_error(y_test, y_pred))
  print("RMSE: ", np.sqrt(mean_squared_error(y_test, y_pred)))

  print("R2: ", r2_score(y_test, y_pred))
  print("MAPE: ", mean_absolute_percentage_error(y_test, y_pred))

In [144]:
show_metrics(y_test, linear_regressor(X_train, y_train, X_test))

MSE:  410286.4041173391
MAE:  450.05088657659104
MAX_ERROR:  6702.3390785467955
RMSE:  640.5360287425987
R2:  0.5104727161832069
MAPE:  135832570554102.94

In [145]:
#show_metrics(y_test, knn_regressor(X_train, y_train, X_test))

Чтож, метрики у knn лучше по MAE, RMSE, R2. Значит модель описывает ценность клиента методом ближайших соседей точнее чем линейной регрессией. По крайней мере, по текущему набору признаков.

Также видно что MAPE имеет несвойственное значение. Пожалуй, это может быть связано с числом маленьких чисел (и даже нулей) при анализе. Проверим это, попробуем посчитать теже метрики, "отбросив" нули.

Переработаем функцию вывода метрик в виде конструктора, где требуемые метрики подаются как аргументы.

In [146]:
metrics = ['MSE', 'MAE', 'MAX_ERROR', 'RMSE', 'R2', 'MAPE']

def show_metrics(y_test, y_pred, metrics: list[str], make_non_zero=False):
  if 'MSE' in metrics:
    print("MSE: ", mean_squared_error(y_test, y_pred))
  if 'MAE' in metrics:
    print("MAE: ", mean_absolute_error(y_test, y_pred))
  if 'MAX_ERROR' in metrics:
    print("MAX_ERROR: ", max_error(y_test, y_pred))
  if 'RMSE' in metrics:
    print("RMSE: ", np.sqrt(mean_squared_error(y_test, y_pred)))
  if 'R2' in metrics:
    print("R2: ", r2_score(y_test, y_pred))
  if 'MAPE' in metrics:
    # используем метрику MAPE только при отсутсвии нулей
    if make_non_zero:
      y_test = y_test[y_test != 0]
      y_pred = y_pred[y_pred != 0][:len(y_test)]
      print("MAPE: ", mean_absolute_percentage_error(y_test, y_pred))

Датасет без нулей.

In [147]:
show_metrics(y_test, linear_regressor(X_train, y_train, X_test), metrics, True)

MSE:  410286.4041173391
MAE:  450.05088657659104
MAX_ERROR:  6702.3390785467955
RMSE:  640.5360287425987
R2:  0.5104727161832069
MAPE:  0.7286854340777977

Для удобной работы с метриками и вычисления их разницы между разними методами добавим представление метрик в виде класса.

In [148]:

class Metrics():
  def __init__(self, y_test,
               y_pred,
               metrics=['MSE', 'MAE', 'MAX_ERROR', 'RMSE', 'R2', 'MAPE'],
               ) -> None:
    self.y_test = y_test
    self.y_pred = y_pred

    self.metrics = metrics
    #self.make_non_zero = make_non_zero

    #метрики
    self.MSE = None
    self.MAE = None
    self.MAX_ERROR = None
    self.RMSE = None
    self.R2 = None
    self.MAPE = None


  def get_metrics(self, make_non_zero=False):
    if 'MSE' in metrics:
      self.MSE = mean_squared_error(self.y_test, self.y_pred)
    if 'MAE' in metrics:
      self.MAE = mean_absolute_error(self.y_test, self.y_pred)
    if 'MAX_ERROR' in metrics:
      self.MAX_ERROR = max_error(self.y_test, self.y_pred)
    if 'RMSE' in metrics:
      self.RMSE = np.sqrt(mean_squared_error(self.y_test, self.y_pred))
    if 'R2' in metrics:
      self.R2 = r2_score(self.y_test, self.y_pred)
    if 'MAPE' in metrics:
      # используем метрику MAPE только при отсутсвии нулей
      if make_non_zero:
        mask = self.y_test != 0
        y_test_ = self.y_test[mask]
        y_pred_ = self.y_pred[mask][:len(y_test)]
        self.MAPE = mean_absolute_percentage_error(y_test_, y_pred_)

    return self

  def __str__(self):
    return f" MSE: {self.MSE} \n MAE: {self.MAE} \n MAX_ERROR: {self.MAX_ERROR} \n RMSE: {self.RMSE} \n R2: {self.R2} \n MAPE: {self.MAPE}"

Проверка на реализованных моделях.

In [149]:
lr_metrics = Metrics(y_test=y_test, y_pred=linear_regressor(X_train, y_train, X_test)).get_metrics()
print(lr_metrics)

 MSE: 410286.4041173391
 MAE: 450.05088657659104
 MAX_ERROR: 6702.3390785467955
 RMSE: 640.5360287425987
 R2: 0.5104727161832069
 MAPE: None

In [150]:
lr_metrics = Metrics(y_test=y_test, y_pred=linear_regressor(X_train, y_train, X_test)).get_metrics(True)
print(lr_metrics)

 MSE: 410286.4041173391
 MAE: 450.05088657659104
 MAX_ERROR: 6702.3390785467955
 RMSE: 640.5360287425987
 R2: 0.5104727161832069
 MAPE: 0.40803091330677743

In [151]:
#show_metrics(y_test, knn_regressor(X_train, y_train, X_test))

TypeError: show_metrics() missing 1 required positional argument: 'metrics'

In [152]:
lr_metrics = Metrics(y_test=y_test, y_pred=knn_regressor(X_train, y_train, X_test)).get_metrics()
print(lr_metrics)

 MSE: 301588.41481668776
 MAE: 393.7439396666667
 MAX_ERROR: 4414.9766666666665
 RMSE: 549.1706609212547
 R2: 0.6401641486184791
 MAPE: None

In [153]:
lr_metrics = Metrics(y_test=y_test, y_pred=knn_regressor(X_train, y_train, X_test)).get_metrics(True)
print(lr_metrics)

 MSE: 301588.41481668776
 MAE: 393.7439396666667
 MAX_ERROR: 4414.9766666666665
 RMSE: 549.1706609212547
 R2: 0.6401641486184791
 MAPE: 0.3577557079101621

Сравнивать метрики разных моделей теперь гораздо удобнее.